const speakeasy = require('speakeasy');
const QRCode = require('qrcode');

/**
 * Generates a new MFA Secret for a user.
 * @param {string} username - User identifier
 * @returns {object} Secret object with ascii, base32, hex, and otpauth_url
 */
function generateMfaSecret(username) {
  return speakeasy.generateSecret({
    name: `AuthGuard-MFA:${username}`,
    issuer: 'AuthGuard-Cloud'
  });
}

/**
 * Generates a QR Code data URL for scanning in authenticator apps.
 * @param {string} otpauthUrl - OTP auth URL generated by speakeasy
 * @returns {Promise<string>} Base64 Data URL for the QR code image
 */
async function generateQrCode(otpauthUrl) {
  try {
    return await QRCode.toDataURL(otpauthUrl);
  } catch (err) {
    throw new Error('Failed to generate QR Code: ' + err.message);
  }
}

/**
 * Verifies a 6-digit TOTP token against the user's secret.
 * @param {string} secret - The user's base32 MFA secret
 * @param {string} token - The 6-digit input token
 * @returns {boolean} True if verified, false otherwise
 */
function verifyMfaToken(secret, token) {
  return speakeasy.totp.verify({
    secret: secret,
    encoding: 'base32',
    token: token,
    window: 10 // Increase window to 10 (allows +/- 5 minutes drift) to ensure demo works smoothly regardless of client clock sync issues
  });
}

module.exports = {
  generateMfaSecret,
  generateQrCode,
  verifyMfaToken
};
